branchName: "chistock-#${issue.number}"
autoCloseIssue: true
openDraftPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true

branches:
  - label: ğŸŒ Deploy
    prefix: deploy/
  - label: âš™ Setting
    prefix: Setting/
  - label: ğŸ BugFix	
    prefix: BugFix/
  - label: ğŸ’» CrossBrowsing
    prefix: CrossBrowsing/
  - label: ğŸ“ƒ Docs
    prefix: Docs/
  - label: âœ¨ Feature
    prefix: feature/
  - label: ğŸ“¬ API
    prefix: API/
  - label: ğŸ“ Modify
    prefix: Modify/
  - label: ğŸ”¨ Refactor
    prefix: Refactor/
  - label: ğŸ¨ Publish
    prefix: Publish/
